***Importing Libraries***

In [4]:
import numpy as np 

In [5]:
from numpy import genfromtxt 

***Importing Data***

In [6]:
data = genfromtxt(r'C:\Users\user\Desktop\bank_note_data.txt', delimiter=',')

In [7]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

***Labels and Features***

In [8]:
labels = data[:,4]

In [9]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [10]:
features = data [:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
x = features 
y = labels

***Train Test Split***

In [12]:
from sklearn.model_selection import train_test_split 

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20, random_state=42)

In [14]:
x_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [15]:
x_test

array([[ 1.5691  ,  6.3465  , -0.1828  , -2.4099  ],
       [-0.27802 ,  8.1881  , -3.1338  , -2.5276  ],
       [ 0.051979,  7.0521  , -2.0541  , -3.1508  ],
       ...,
       [ 3.4626  , -4.449   ,  3.5427  ,  0.15429 ],
       [-0.278   ,  8.1881  , -3.1338  , -2.5276  ],
       [ 2.7831  , 10.9796  , -3.557   , -4.4039  ]])

In [16]:
y_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 0.

In [17]:
y_train

array([0., 0., 1., ..., 1., 1., 1.])

***Standardizing the Data***

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaler_object=MinMaxScaler()

In [20]:
scaler_object.fit(x_train)

MinMaxScaler()

In [21]:
scaled_x_train=scaler_object.transform(x_train)

In [22]:
scaled_x_test=scaler_object.transform(x_test)

In [23]:
x_train.max()

17.9274

In [24]:
scaled_x_train.max()

1.0000000000000002

In [25]:
scaled_x_train

array([[4.07704678e-01, 9.83199063e-01, 2.56697443e-01, 9.33178971e-02],
       [7.07908761e-01, 7.71971248e-01, 1.80872580e-01, 8.05140280e-01],
       [1.98559159e-01, 2.21136252e-01, 7.37428144e-01, 6.20911798e-01],
       ...,
       [4.11050776e-04, 8.63104170e-01, 2.34046756e-01, 3.74261253e-01],
       [2.58284115e-01, 6.16029366e-01, 2.33861752e-01, 7.02643151e-01],
       [2.65661395e-01, 2.44444278e-01, 7.20316361e-01, 7.44775785e-01]])

In [26]:
x_train

array([[-1.3885  , 12.5026  ,  0.69118 , -7.5487  ],
       [ 2.7744  ,  6.8576  , -1.0671  ,  0.075416],
       [-4.2887  , -7.8633  , 11.8387  , -1.8978  ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

***Building the model***

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [29]:
model = Sequential()


model.add(Dense(4, input_dim=4, activation='leaky_relu'))

model.add(Dense(8, activation='leaky_relu'))

model.add(Dense(1, activation='sigmoid'))

***Compiling Model***

In [59]:
model.compile(loss='KLDivergence', optimizer='SGD', metrics=['accuracy'])

In [61]:
model.fit(scaled_x_train, y_train, epochs=10, verbose=2)

Epoch 1/10
35/35 - 0s - loss: 7.7024e-05 - accuracy: 0.8022 - 68ms/epoch - 2ms/step
Epoch 2/10
35/35 - 0s - loss: 7.5690e-05 - accuracy: 0.7995 - 78ms/epoch - 2ms/step
Epoch 3/10
35/35 - 0s - loss: 7.4400e-05 - accuracy: 0.7976 - 78ms/epoch - 2ms/step
Epoch 4/10
35/35 - 0s - loss: 7.3156e-05 - accuracy: 0.7967 - 78ms/epoch - 2ms/step
Epoch 5/10
35/35 - 0s - loss: 7.1955e-05 - accuracy: 0.7958 - 69ms/epoch - 2ms/step
Epoch 6/10
35/35 - 0s - loss: 7.0659e-05 - accuracy: 0.7931 - 77ms/epoch - 2ms/step
Epoch 7/10
35/35 - 0s - loss: 6.9533e-05 - accuracy: 0.7912 - 65ms/epoch - 2ms/step
Epoch 8/10
35/35 - 0s - loss: 6.8299e-05 - accuracy: 0.7912 - 71ms/epoch - 2ms/step
Epoch 9/10
35/35 - 0s - loss: 6.7199e-05 - accuracy: 0.7876 - 76ms/epoch - 2ms/step
Epoch 10/10
35/35 - 0s - loss: 6.6102e-05 - accuracy: 0.7867 - 76ms/epoch - 2ms/step


In [62]:
scaled_x_test

array([[0.62098955, 0.75284662, 0.21900753, 0.5730998 ],
       [0.48778602, 0.82175665, 0.09174727, 0.56211079],
       [0.51158363, 0.77924916, 0.13830875, 0.50392598],
       ...,
       [0.75753773, 0.34889447, 0.37966768, 0.81250432],
       [0.48778747, 0.82175665, 0.09174727, 0.56211079],
       [0.70853615, 0.92621058, 0.07349701, 0.38693083]])

In [63]:
model.predict(scaled_x_test)

9/9 [==============================] - 0s 2ms/step


array([[0.33972803],
       [0.998918  ],
       [0.98725677],
       [0.00651975],
       [0.925284  ],
       [0.3333779 ],
       [0.52754414],
       [0.67350465],
       [0.5013062 ],
       [0.17560676],
       [0.9999568 ],
       [0.9999969 ],
       [0.18424618],
       [0.9996579 ],
       [0.8460895 ],
       [0.99990517],
       [0.999952  ],
       [0.9999642 ],
       [0.9999757 ],
       [0.9990169 ],
       [0.6911363 ],
       [0.07530719],
       [0.99980265],
       [0.8182582 ],
       [0.9999991 ],
       [0.75868714],
       [0.04028941],
       [0.99980026],
       [0.02745244],
       [0.15627457],
       [0.9999887 ],
       [0.16165365],
       [0.43990174],
       [0.99998194],
       [0.99999446],
       [0.33200112],
       [0.99994737],
       [0.99999255],
       [0.9999969 ],
       [0.11394259],
       [0.015758  ],
       [0.99997663],
       [0.99998695],
       [0.7691769 ],
       [0.9999995 ],
       [0.9999095 ],
       [0.9999973 ],
       [0.390

***Evaluation Model***

In [64]:
model.metrics_names

['loss', 'accuracy']

In [65]:
model.evaluate(x=scaled_x_test, y=y_test)

9/9 [==============================] - 0s 3ms/step - loss: 6.8287e-05 - accuracy: 0.7564


[6.82867321302183e-05, 0.7563636302947998]

In [66]:
from sklearn.metrics import confusion_matrix, classification_report

In [67]:
predict_x = model.predict(scaled_x_test)
classes_x = np.argmax(predict_x, axis=1)

9/9 [==============================] - 0s 1ms/step


In [68]:
classes_x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [69]:
confusion_matrix(y_test, classes_x)

array([[148,   0],
       [127,   0]], dtype=int64)

In [70]:
predictions = (model.predict(scaled_x_test) > 0.5).astype("int32") 

9/9 [==============================] - 0s 2ms/step


In [49]:
predictions

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [71]:
confusion_matrix(y_test,predictions)

array([[ 81,  67],
       [  0, 127]], dtype=int64)

In [72]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       1.00      0.55      0.71       148
         1.0       0.65      1.00      0.79       127

    accuracy                           0.76       275
   macro avg       0.83      0.77      0.75       275
weighted avg       0.84      0.76      0.75       275

